# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Blue Coat Dev
tagline:          'Writing my thoughts'
description:      'Made by <a href="https://twitter.com/bluecoatdev" target="_blank">@bluecoatdev</a>.'
url:              http://r3dswitch.github.io
baseurl:          /

author:
  name:           'Soumya Mondal'
  url:            https://twitter.com/bluecoatdev

paginate:         5
plugins: [jekyll-paginate]
gems: [jekyll-gist]

# Custom vars

github:
  repo:           https://github.com/r3dswitch.github.io
